version: "3.7"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rd-portfolio-dev
    restart: on-failure
    ports:
      - "3002:3000"

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: rd-portfolio-prod
    restart: on-failure
    ports:
      - "3001:3000"

volumes:
  node_modules: